---
- name: Hello simple message
  hosts: all
  tasks:
    - name: Print message
      debug:
        msg: I Enjoy Sys Automation
    - name: Systems name
      command: "uname -a"
      register: uname
    - name: Print Hostname
      debug:
        msg: uname
