---
- name: Hello simple message
  hosts: all
  tasks:
    - name: Print message
      debug:
        msg: I Enjoy Sys Automation
    - name: Print all available facts
      debug:
        var: ansible_facts
#   - name: "Ansible | Print a variable"
#     debug:
#       msg: "The operating system is {{ ansible_distribution }}"
    - name: "Ansible | Print a variable"
      debug:
        msg: "The operating system is {{ ansible_facts['nodename'] }}"
